apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: wooglife
spec:
  revisionHistoryLimit: 1
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/woog-life/preliminary-frontend:{{TAG}}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
