name: Build and deploy

on:
  pull_request:
  push:
    branches:
      - '!master'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update tag in manifest.yml
        run: sed -i -e "s#__TAG__#${GITHUB_SHA}#g" values.yaml
      - uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}
      - uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint --strict
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t ghcr.io/woog-life/preliminary-frontend:${GITHUB_SHA} .
      - name: Cypress tests
        uses: cypress-io/github-action@v2
        with:
          start: docker run --rm -p 8080:80 ghcr.io/woog-life/preliminary-frontend:${GITHUB_SHA}
          wait-on: 'http://localhost:8080'
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
